// Mocks generated by Mockito 5.4.4 from annotations
// in jazmine_calendar/test/event_display_widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:ui' as _i8;

import 'package:flutter/material.dart' as _i2;
import 'package:jazmine_calendar/src/controller/calendar_controller.dart'
    as _i3;
import 'package:jazmine_calendar/src/enums/enums.dart' as _i4;
import 'package:jazmine_calendar/src/models/calendar_event.dart' as _i5;
import 'package:jazmine_calendar/src/persistence/calendar_persistence.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeValueNotifier_0<T> extends _i1.SmartFake
    implements _i2.ValueNotifier<T> {
  _FakeValueNotifier_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDateTime_1 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTimeOfDay_2 extends _i1.SmartFake implements _i2.TimeOfDay {
  _FakeTimeOfDay_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CalendarController].
///
/// See the documentation for Mockito's code generation for more information.
class MockCalendarController extends _i1.Mock
    implements _i3.CalendarController {
  MockCalendarController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get firstDayOfWeek => (super.noSuchMethod(
        Invocation.getter(#firstDayOfWeek),
        returnValue: 0,
      ) as int);

  @override
  _i2.ValueNotifier<_i4.CalendarViewType> get currentViewNotifier =>
      (super.noSuchMethod(
        Invocation.getter(#currentViewNotifier),
        returnValue: _FakeValueNotifier_0<_i4.CalendarViewType>(
          this,
          Invocation.getter(#currentViewNotifier),
        ),
      ) as _i2.ValueNotifier<_i4.CalendarViewType>);

  @override
  _i2.ValueNotifier<DateTime> get selectedDateNotifier => (super.noSuchMethod(
        Invocation.getter(#selectedDateNotifier),
        returnValue: _FakeValueNotifier_0<DateTime>(
          this,
          Invocation.getter(#selectedDateNotifier),
        ),
      ) as _i2.ValueNotifier<DateTime>);

  @override
  _i2.ValueNotifier<DateTime> get startDateNotifier => (super.noSuchMethod(
        Invocation.getter(#startDateNotifier),
        returnValue: _FakeValueNotifier_0<DateTime>(
          this,
          Invocation.getter(#startDateNotifier),
        ),
      ) as _i2.ValueNotifier<DateTime>);

  @override
  _i2.ValueNotifier<DateTime> get currentTimeNotifier => (super.noSuchMethod(
        Invocation.getter(#currentTimeNotifier),
        returnValue: _FakeValueNotifier_0<DateTime>(
          this,
          Invocation.getter(#currentTimeNotifier),
        ),
      ) as _i2.ValueNotifier<DateTime>);

  @override
  _i2.ValueNotifier<Duration> get intervalNotifier => (super.noSuchMethod(
        Invocation.getter(#intervalNotifier),
        returnValue: _FakeValueNotifier_0<Duration>(
          this,
          Invocation.getter(#intervalNotifier),
        ),
      ) as _i2.ValueNotifier<Duration>);

  @override
  _i4.CalendarViewType get currentView => (super.noSuchMethod(
        Invocation.getter(#currentView),
        returnValue: _i4.CalendarViewType.day,
      ) as _i4.CalendarViewType);

  @override
  DateTime get selectedDate => (super.noSuchMethod(
        Invocation.getter(#selectedDate),
        returnValue: _FakeDateTime_1(
          this,
          Invocation.getter(#selectedDate),
        ),
      ) as DateTime);

  @override
  DateTime get startDate => (super.noSuchMethod(
        Invocation.getter(#startDate),
        returnValue: _FakeDateTime_1(
          this,
          Invocation.getter(#startDate),
        ),
      ) as DateTime);

  @override
  List<String> get visibleTimeZones => (super.noSuchMethod(
        Invocation.getter(#visibleTimeZones),
        returnValue: <String>[],
      ) as List<String>);

  @override
  bool get showFloatingActionButton => (super.noSuchMethod(
        Invocation.getter(#showFloatingActionButton),
        returnValue: false,
      ) as bool);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get hasInitialScroll => (super.noSuchMethod(
        Invocation.getter(#hasInitialScroll),
        returnValue: false,
      ) as bool);

  @override
  _i2.ValueNotifier<List<_i5.CalendarEvent>> get eventsNotifier =>
      (super.noSuchMethod(
        Invocation.getter(#eventsNotifier),
        returnValue: _FakeValueNotifier_0<List<_i5.CalendarEvent>>(
          this,
          Invocation.getter(#eventsNotifier),
        ),
      ) as _i2.ValueNotifier<List<_i5.CalendarEvent>>);

  @override
  bool get scrollToCurrentTimeOnLoad => (super.noSuchMethod(
        Invocation.getter(#scrollToCurrentTimeOnLoad),
        returnValue: false,
      ) as bool);

  @override
  bool get animateTimeScroll => (super.noSuchMethod(
        Invocation.getter(#animateTimeScroll),
        returnValue: false,
      ) as bool);

  @override
  List<_i2.TimeOfDay> get defaultStartTimes => (super.noSuchMethod(
        Invocation.getter(#defaultStartTimes),
        returnValue: <_i2.TimeOfDay>[],
      ) as List<_i2.TimeOfDay>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void setInitialScrollComplete() => super.noSuchMethod(
        Invocation.method(
          #setInitialScrollComplete,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setShowFloatingActionButton(bool? show) => super.noSuchMethod(
        Invocation.method(
          #setShowFloatingActionButton,
          [show],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setOnEventCreated(_i3.EventCallback? callback) => super.noSuchMethod(
        Invocation.method(
          #setOnEventCreated,
          [callback],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setOnEventRescheduled(_i3.EventTimeCallback? callback) =>
      super.noSuchMethod(
        Invocation.method(
          #setOnEventRescheduled,
          [callback],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setOnEventResized(_i3.EventTimeCallback? callback) => super.noSuchMethod(
        Invocation.method(
          #setOnEventResized,
          [callback],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setPersistence(_i6.CalendarPersistence? persistence) =>
      super.noSuchMethod(
        Invocation.method(
          #setPersistence,
          [persistence],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void changeView(_i4.CalendarViewType? view) => super.noSuchMethod(
        Invocation.method(
          #changeView,
          [view],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void selectDate(DateTime? date) => super.noSuchMethod(
        Invocation.method(
          #selectDate,
          [date],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void navigateToDate(DateTime? date) => super.noSuchMethod(
        Invocation.method(
          #navigateToDate,
          [date],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void navigateToNextPage() => super.noSuchMethod(
        Invocation.method(
          #navigateToNextPage,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void navigateToPreviousPage() => super.noSuchMethod(
        Invocation.method(
          #navigateToPreviousPage,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setTargetHour(int? hour) => super.noSuchMethod(
        Invocation.method(
          #setTargetHour,
          [hour],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setInterval(Duration? interval) => super.noSuchMethod(
        Invocation.method(
          #setInterval,
          [interval],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<void> addEvent(_i5.CalendarEvent? event) => (super.noSuchMethod(
        Invocation.method(
          #addEvent,
          [event],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> updateEvent(_i5.CalendarEvent? event) => (super.noSuchMethod(
        Invocation.method(
          #updateEvent,
          [event],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> deleteEvent(_i5.CalendarEvent? event) => (super.noSuchMethod(
        Invocation.method(
          #deleteEvent,
          [event],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i5.CalendarEvent>> getAllEvents() => (super.noSuchMethod(
        Invocation.method(
          #getAllEvents,
          [],
        ),
        returnValue:
            _i7.Future<List<_i5.CalendarEvent>>.value(<_i5.CalendarEvent>[]),
      ) as _i7.Future<List<_i5.CalendarEvent>>);

  @override
  _i7.Future<void> clearEvents() => (super.noSuchMethod(
        Invocation.method(
          #clearEvents,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> rescheduleEvent(
    _i5.CalendarEvent? event,
    DateTime? newStart,
    DateTime? newEnd,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #rescheduleEvent,
          [
            event,
            newStart,
            newEnd,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void addTimeZone(String? timeZone) => super.noSuchMethod(
        Invocation.method(
          #addTimeZone,
          [timeZone],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeTimeZone(String? timeZone) => super.noSuchMethod(
        Invocation.method(
          #removeTimeZone,
          [timeZone],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void invalidateCache() => super.noSuchMethod(
        Invocation.method(
          #invalidateCache,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  double? getScrollPosition(_i4.CalendarViewType? view) =>
      (super.noSuchMethod(Invocation.method(
        #getScrollPosition,
        [view],
      )) as double?);

  @override
  void setScrollPosition(
    _i4.CalendarViewType? view,
    double? position,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setScrollPosition,
          [
            view,
            position,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setAnimateTimeScroll(bool? value) => super.noSuchMethod(
        Invocation.method(
          #setAnimateTimeScroll,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.TimeOfDay getStartTimeForDay(DateTime? date) => (super.noSuchMethod(
        Invocation.method(
          #getStartTimeForDay,
          [date],
        ),
        returnValue: _FakeTimeOfDay_2(
          this,
          Invocation.method(
            #getStartTimeForDay,
            [date],
          ),
        ),
      ) as _i2.TimeOfDay);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
